/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

/**
 *
 * @author dafuentes
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btn_sesion = new javax.swing.JButton();
        btn_pedido = new javax.swing.JButton();
        btn_devolucion = new javax.swing.JButton();
        btn_historial = new javax.swing.JButton();
        nuevoPedido = new javax.swing.JLabel();
        nuevaDevolucion = new javax.swing.JLabel();
        pedidos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 370));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("MENÚ CLIENTE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btn_sesion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion.setBorderPainted(false);
        btn_sesion.setContentAreaFilled(false);
        btn_sesion.setFocusPainted(false);
        btn_sesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 40, -1));

        btn_pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        btn_pedido.setBorderPainted(false);
        btn_pedido.setContentAreaFilled(false);
        btn_pedido.setFocusPainted(false);
        btn_pedido.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy pressed.png"))); // NOI18N
        btn_pedido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy pressed.png"))); // NOI18N
        btn_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 66, 66));

        btn_devolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        btn_devolucion.setBorderPainted(false);
        btn_devolucion.setContentAreaFilled(false);
        btn_devolucion.setFocusPainted(false);
        btn_devolucion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return pressed.png"))); // NOI18N
        btn_devolucion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return pressed.png"))); // NOI18N
        btn_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolucionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 66, 66));

        btn_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N
        btn_historial.setBorderPainted(false);
        btn_historial.setContentAreaFilled(false);
        btn_historial.setFocusPainted(false);
        btn_historial.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos pressed.png"))); // NOI18N
        btn_historial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos pressed.png"))); // NOI18N
        btn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historialActionPerformed(evt);
            }
        });
        getContentPane().add(btn_historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 72, 66));

        nuevoPedido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nuevoPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoPedido.setText("Nuevo Pedido");
        getContentPane().add(nuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        nuevaDevolucion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nuevaDevolucion.setText("Nueva Devolución");
        getContentPane().add(nuevaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        pedidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pedidos.setText("Pedidos");
        getContentPane().add(pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesionActionPerformed
        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesionActionPerformed

    private void btn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historialActionPerformed
        VentanaHistorial historial = new VentanaHistorial();
        historial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_historialActionPerformed

    private void btn_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidoActionPerformed
        VentanaPedido pedido = new VentanaPedido();
        pedido.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pedidoActionPerformed

    private void btn_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolucionActionPerformed
        VentanaDevolucion devolucion = new VentanaDevolucion();
        devolucion.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_devolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_devolucion;
    private javax.swing.JButton btn_historial;
    private javax.swing.JButton btn_pedido;
    private javax.swing.JButton btn_sesion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nuevaDevolucion;
    private javax.swing.JLabel nuevoPedido;
    private javax.swing.JLabel pedidos;
    // End of variables declaration//GEN-END:variables
}
