/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

/**
 *
 * @author dafuentes
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_articulo = new javax.swing.JButton();
        btn_pedido = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        reportes = new javax.swing.JLabel();
        nuevoArt1 = new javax.swing.JLabel();
        estadoPedido1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sesion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion.setBorderPainted(false);
        btn_sesion.setContentAreaFilled(false);
        btn_sesion.setFocusPainted(false);
        btn_sesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 40, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setText("MENÚ ADMINISTRADOR");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btn_articulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics (1).png"))); // NOI18N
        btn_articulo.setBorderPainted(false);
        btn_articulo.setContentAreaFilled(false);
        btn_articulo.setFocusPainted(false);
        btn_articulo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics pressed.png"))); // NOI18N
        btn_articulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics pressed.png"))); // NOI18N
        btn_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_articuloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 70));

        btn_pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tasks.png"))); // NOI18N
        btn_pedido.setBorderPainted(false);
        btn_pedido.setContentAreaFilled(false);
        btn_pedido.setFocusPainted(false);
        btn_pedido.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tasks pressed.png"))); // NOI18N
        btn_pedido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tasks pressed.png"))); // NOI18N
        btn_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, 70));

        btn_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clipboard.png"))); // NOI18N
        btn_reporte.setBorderPainted(false);
        btn_reporte.setContentAreaFilled(false);
        btn_reporte.setFocusPainted(false);
        btn_reporte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clipboard pressed.png"))); // NOI18N
        btn_reporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clipboard pressed.png"))); // NOI18N
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, 70));

        reportes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("Reportes");
        getContentPane().add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, -1));

        nuevoArt1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nuevoArt1.setText("Nuevo Artículo");
        getContentPane().add(nuevoArt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        estadoPedido1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        estadoPedido1.setText("Estado Pedido");
        getContentPane().add(estadoPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesionActionPerformed
        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesionActionPerformed

    private void btn_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_articuloActionPerformed
        VentanaArticulo ventanaArticulo = new VentanaArticulo();
        ventanaArticulo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_articuloActionPerformed

    private void btn_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidoActionPerformed
        VentanaEstado ventanaEstado = new VentanaEstado();
        ventanaEstado.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pedidoActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        VentanaReporte reporte = new VentanaReporte();
        reporte.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_articulo;
    private javax.swing.JButton btn_pedido;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_sesion;
    private javax.swing.JLabel estadoPedido1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nuevoArt1;
    private javax.swing.JLabel reportes;
    // End of variables declaration//GEN-END:variables
}
