/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

import javax.swing.table.DefaultTableModel;
import org.inventario.bean.Entrega;
import org.inventario.bean.SubPedido;
import org.inventario.controlador.ControladorEntrega;
import org.inventario.controlador.ControladorPedido;
import org.inventario.controlador.ControladorSubPedido;

/**
 *
 * @author dafuentes
 */
public class ReporteEstado extends javax.swing.JFrame {
    
    private ControladorEntrega ctl_entrega = new ControladorEntrega().getInstance();
    private ControladorPedido ctl_pedido = new ControladorPedido().getInstance();
    private ControladorSubPedido ctl_subPedido = new ControladorSubPedido().getInstance();
    /**
     * Creates new form ReporteEstado
     */
    public ReporteEstado() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sesion4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entrega = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sesion4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion4.setBorderPainted(false);
        btn_sesion4.setContentAreaFilled(false);
        btn_sesion4.setFocusPainted(false);
        btn_sesion4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesion4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 35, 35));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("REPORTE DE PEDIDOS POR DÍA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, -1, -1));

        tbl_entrega.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbl_entrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Correlativo", "Artículo", "Estado", "Fecha de Entrega"
            }
        ));
        tbl_entrega.setEnabled(false);
        tbl_entrega.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbl_entrega);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 551, 313));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 100, -1, -1));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "INICIADO", "EN PROCESO", "ENTREGADO" }));
        getContentPane().add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 101, 126, -1));

        btn_buscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setBorderPainted(false);
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.setFocusPainted(false);
        btn_buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search pressed.png"))); // NOI18N
        btn_buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search pressed.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 90, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesion4ActionPerformed
        VentanaReporte ventana = new VentanaReporte();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesion4ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_entrega.getModel();
        model.setRowCount(0);
        for (Entrega t : ctl_entrega.consultaReporteEstado(cmb_estado.getSelectedItem().toString())) {
            String productos = "| ";
            for (SubPedido objeto: ctl_subPedido.buscar(t.getPedido().getId())) {
                productos += objeto.getArticulo().getNombre() + " | ";
            }
            Object rowData[] = {t.getId(), productos, t.getEstado(), t.getPedido().getFechaEntrega() };
            model.addRow(rowData);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteEstado().setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        DefaultTableModel model = (DefaultTableModel) tbl_entrega.getModel();
        for (Entrega t : ctl_entrega.getListado()) {
            String productos = "| ";
            for (SubPedido objeto: ctl_subPedido.buscar(t.getPedido().getId())) {
                productos += objeto.getArticulo().getNombre() + " | ";
            }
            Object rowData[] = {t.getId(), productos, t.getEstado(), t.getPedido().getFechaEntrega() };
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_sesion4;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_entrega;
    // End of variables declaration//GEN-END:variables
}
