/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

import javax.swing.table.DefaultTableModel;
import org.inventario.bean.Entrega;
import org.inventario.bean.SubPedido;
import org.inventario.controlador.ControladorEntrega;
import org.inventario.controlador.ControladorSubPedido;

/**
 *
 * @author dafuentes
 */
public class VentanaHistorial extends javax.swing.JFrame {
    
    private ControladorEntrega ctl_entrega = new ControladorEntrega().getInstance();
    private ControladorSubPedido ctl_subPedido = new ControladorSubPedido().getInstance();

    /**
     * Creates new form Historiak
     */
    public VentanaHistorial() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sesion3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entrega = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(626, 505));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(626, 505));
        setResizable(false);
        setSize(new java.awt.Dimension(626, 505));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sesion3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion3.setBorderPainted(false);
        btn_sesion3.setContentAreaFilled(false);
        btn_sesion3.setFocusPainted(false);
        btn_sesion3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesion3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 35, 35));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("HISTORIAL");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 11, -1, -1));

        tbl_entrega.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbl_entrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Correlativo", "Artículo", "Estado", "Fecha de Entrega"
            }
        ));
        tbl_entrega.setEnabled(false);
        tbl_entrega.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbl_entrega);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, 551, 360));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesion3ActionPerformed
        MenuCliente menuCliente = new MenuCliente();
        menuCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHistorial().setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        DefaultTableModel model = (DefaultTableModel) tbl_entrega.getModel();
        for (Entrega t : ctl_entrega.buscar()) {
            String productos = "| ";
            for (SubPedido objeto: ctl_subPedido.buscar(t.getPedido().getId())) {
                productos += objeto.getArticulo().getNombre() + " | ";
            }
            Object rowData[] = {t.getId(), productos, t.getEstado(), t.getPedido().getFechaEntrega() };
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sesion3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_entrega;
    // End of variables declaration//GEN-END:variables
}
