/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

/**
 *
 * @author dafuentes
 */
public class VentanaReporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public VentanaReporte() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_reporteDia = new javax.swing.JButton();
        btn_reporteEstado = new javax.swing.JButton();
        btn_reporteDevolucion = new javax.swing.JButton();
        btn_reporteArticulo = new javax.swing.JButton();
        dia = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        devoluciones = new javax.swing.JLabel();
        articulos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 370));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sesion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion.setBorderPainted(false);
        btn_sesion.setContentAreaFilled(false);
        btn_sesion.setFocusPainted(false);
        btn_sesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 37, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 11, 155, -1));

        btn_reporteDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documents.png"))); // NOI18N
        btn_reporteDia.setBorderPainted(false);
        btn_reporteDia.setContentAreaFilled(false);
        btn_reporteDia.setFocusPainted(false);
        btn_reporteDia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documents PRESSED.png"))); // NOI18N
        btn_reporteDia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documents PRESSED.png"))); // NOI18N
        btn_reporteDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteDiaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporteDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 67, -1));

        btn_reporteEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speedometer.png"))); // NOI18N
        btn_reporteEstado.setBorderPainted(false);
        btn_reporteEstado.setContentAreaFilled(false);
        btn_reporteEstado.setFocusPainted(false);
        btn_reporteEstado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speedometer PRESSED.png"))); // NOI18N
        btn_reporteEstado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speedometer PRESSED.png"))); // NOI18N
        btn_reporteEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 66, -1));

        btn_reporteDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return (1).png"))); // NOI18N
        btn_reporteDevolucion.setBorderPainted(false);
        btn_reporteDevolucion.setContentAreaFilled(false);
        btn_reporteDevolucion.setFocusPainted(false);
        btn_reporteDevolucion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return (1) PRESSED.png"))); // NOI18N
        btn_reporteDevolucion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return (1) PRESSED.png"))); // NOI18N
        btn_reporteDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteDevolucionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporteDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 68, -1));

        btn_reporteArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trolley.png"))); // NOI18N
        btn_reporteArticulo.setBorderPainted(false);
        btn_reporteArticulo.setContentAreaFilled(false);
        btn_reporteArticulo.setFocusPainted(false);
        btn_reporteArticulo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trolley PRESSED.png"))); // NOI18N
        btn_reporteArticulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trolley PRESSED.png"))); // NOI18N
        btn_reporteArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporteArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 67, -1));

        dia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dia.setText("Reporte por Día");
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        estado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        estado.setText("Reporte de Estado");
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        devoluciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        devoluciones.setText("Reporte de Devoluciones");
        getContentPane().add(devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        articulos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        articulos.setText("Reporte de Artículos");
        getContentPane().add(articulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesionActionPerformed
        MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesionActionPerformed

    private void btn_reporteEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteEstadoActionPerformed
       ReporteEstado reporte = new ReporteEstado();
       reporte.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_reporteEstadoActionPerformed

    private void btn_reporteDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteDiaActionPerformed
       ReporteDevolucion reporte = new ReporteDevolucion();
       reporte.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_reporteDiaActionPerformed

    private void btn_reporteDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteDevolucionActionPerformed
       ReporteDia reporte = new ReporteDia();
       reporte.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_reporteDevolucionActionPerformed

    private void btn_reporteArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteArticuloActionPerformed
       ReporteArticulo reporte = new ReporteArticulo();
       reporte.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_reporteArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel articulos;
    private javax.swing.JButton btn_reporteArticulo;
    private javax.swing.JButton btn_reporteDevolucion;
    private javax.swing.JButton btn_reporteDia;
    private javax.swing.JButton btn_reporteEstado;
    private javax.swing.JButton btn_sesion;
    private javax.swing.JLabel devoluciones;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
