/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

import java.text.DateFormat;
import java.util.Date;
import org.inventario.bean.Articulo;
import org.inventario.bean.ArticuloComboBox;
import org.inventario.bean.Entrega;
import org.inventario.bean.Pedido;
import org.inventario.bean.SubPedido;
import org.inventario.bean.Usuario;
import org.inventario.bean.SubPedidoList;
import org.inventario.controlador.ControladorArticulo;
import org.inventario.controlador.ControladorEntrega;
import org.inventario.controlador.ControladorPedido;
import org.inventario.controlador.ControladorSubPedido;
import org.inventario.controlador.ControladorUsuario;

/**
 *
 * @author dafuentes
 */
public class VentanaPedido extends javax.swing.JFrame {

    private ControladorPedido ctl_pedido = new ControladorPedido().getInstance();
    private ControladorSubPedido ctl_subPedido = new ControladorSubPedido().getInstance();
    private ControladorArticulo ctl_articulo = new ControladorArticulo().getInstance();
    private Usuario usuario = ControladorUsuario.usuario;
    private SubPedidoList list_model = new SubPedidoList().getInstance();
    private ArticuloComboBox cmb_model = new ArticuloComboBox().getInstance();

    /**
     * Creates new form VentanaPedido
     */
    public VentanaPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sesion3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_articulo = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        txt_nombre1 = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        cb_articulo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_nit = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_correlativo = new javax.swing.JTextField();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        btn_finalizar = new javax.swing.JButton();
        finalizar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(667, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(667, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(667, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sesion3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_sesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_sesion3.setBorderPainted(false);
        btn_sesion3.setContentAreaFilled(false);
        btn_sesion3.setFocusPainted(false);
        btn_sesion3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_sesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesion3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 36, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PEDIDO");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, -1));

        list_articulo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        list_articulo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_articuloValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(list_articulo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 216, 190, 182));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Artículos a Enviar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 181, 190, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 71, 15));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 83, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 71, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Nit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 73, 15));

        btn_eliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rubbish.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setFocusPainted(false);
        btn_eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rubbish pressed.png"))); // NOI18N
        btn_eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rubbish pressed.png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        txt_nombre1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 190, -1));

        btn_agregar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setBorderPainted(false);
        btn_agregar.setContentAreaFilled(false);
        btn_agregar.setFocusPainted(false);
        btn_agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1) pressed.png"))); // NOI18N
        btn_agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1) pressed.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Artículo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 103, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 103, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Precio           Q.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Fecha entrega");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txt_cantidad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_cantidad.setText("1");
        txt_cantidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_cantidadInputMethodTextChanged(evt);
            }
        });
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 62, 20));

        txt_precio.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        txt_precio.setText("0.0");
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        txt_precio.setEnabled(false);
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 62, 20));

        cb_articulo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cb_articulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_articuloItemStateChanged(evt);
            }
        });
        cb_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_articuloActionPerformed(evt);
            }
        });
        cb_articulo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_articuloPropertyChange(evt);
            }
        });
        getContentPane().add(cb_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Correlativo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.setEditable(false);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 20));

        txt_telefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.setEditable(false);
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, 20));

        txt_nit.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });
        txt_nit.setEditable(false);
        getContentPane().add(txt_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 99, -1));

        txt_direccion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        txt_direccion.setEditable(false);
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 97, -1));

        txt_correlativo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correlativoActionPerformed(evt);
            }
        });
        txt_correlativo.setEditable(false);
        getContentPane().add(txt_correlativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 23, -1));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, 20));

        btn_finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette.png"))); // NOI18N
        btn_finalizar.setBorderPainted(false);
        btn_finalizar.setContentAreaFilled(false);
        btn_finalizar.setFocusPainted(false);
        btn_finalizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette pressed.png"))); // NOI18N
        btn_finalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette pressed.png"))); // NOI18N
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 70, -1));

        finalizar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        finalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalizar.setText("Finalizar Pedido");
        getContentPane().add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesion3ActionPerformed
        MenuCliente menuCliente = new MenuCliente();
        menuCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sesion3ActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       int selection = list_articulo.getSelectedIndex();
        if (selection!=-1) {
           list_model.eliminar(selection);
           txt_nombre1.setText("");
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void list_articuloValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_articuloValueChanged
        int selection = list_articulo.getSelectedIndex();
        if (selection!=-1) {
            SubPedido p = list_model.getSubPedido(selection);
            txt_nombre1.setText(p.getArticulo().getNombre());
        }
    }//GEN-LAST:event_list_articuloValueChanged

    private void txt_nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre1ActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        int selection = cb_articulo.getSelectedIndex();
        Articulo articulo = null;
        Double precio = 0.0;
        int cantidad = 0;
        if (selection > -1) {
            articulo = cmb_model.getArticulo(selection);
        }
        if (!txt_precio.getText().equals("")) {
            precio = Double.parseDouble(txt_precio.getText());
        }
        if (!txt_cantidad.getText().equals("")) {
            cantidad = Integer.parseInt(txt_cantidad.getText());
        }
        int idPedido = ctl_pedido.getLongitud();
        if (cantidad > 0 && precio > 0.0) {
            SubPedido subPedido = new SubPedido(ctl_subPedido.getLongitud(true), articulo, cantidad, precio, idPedido);
            list_model.agregar(subPedido); 
            cb_articulo.setSelectedIndex(-1);
            cb_articulo.repaint();
            txt_cantidad.setText("1");
            txt_precio.setText("0.00");
            
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void cb_articuloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_articuloItemStateChanged
        
    }//GEN-LAST:event_cb_articuloItemStateChanged

    private void cb_articuloPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_articuloPropertyChange
         // TODO add your handling code here:
    }//GEN-LAST:event_cb_articuloPropertyChange

    private void cb_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_articuloActionPerformed
        int selection = cb_articulo.getSelectedIndex();
        if (selection > -1 && !txt_cantidad.getText().equals("")) {
            Articulo articulo = cmb_model.getArticulo(selection);
            double total =  articulo.getPrecio() * Integer.parseInt(txt_cantidad.getText());
            txt_precio.setText(total + "");
       } else {
           txt_precio.setText("0.00");
       }
    }//GEN-LAST:event_cb_articuloActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_cantidadInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_cantidadInputMethodTextChanged
       
    }//GEN-LAST:event_txt_cantidadInputMethodTextChanged

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }
        int selection = cb_articulo.getSelectedIndex();
        String cantidad = txt_cantidad.getText() + caracter;
        if (selection > -1 && !cantidad.equals("") && caracter != '\b') {
            Articulo articulo = cmb_model.getArticulo(selection);
            double total =  articulo.getPrecio() * Integer.parseInt(cantidad);
            txt_precio.setText(total + "");
        } else {
            txt_precio.setText("0.00");
        }
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        // TODO add your handling code here:
        if (list_model.getSize() > 0 ) {
            try {
                Date date = txt_fecha.getDate();
                String fecha = DateFormat.getDateInstance().format(date);
                Pedido pedido = new Pedido(ctl_pedido.getLongitud(), usuario, fecha);
                ctl_pedido.agregar(pedido);
                for(SubPedido objeto: list_model.getListado()) {
                    ctl_subPedido.agregar(objeto);
                }
                ControladorEntrega ctl_entrega = new ControladorEntrega().getInstance();
                Entrega entrega = new Entrega(ctl_entrega.getLongitud(),"INICIADO", pedido);
                ctl_entrega.agregar(entrega);
                MenuCliente menu = new MenuCliente();
                menu.setVisible(true);
                dispose();
            } catch (NullPointerException ex) {
                System.out.println("Falta Fecha");
            }
        }
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void txt_correlativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correlativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correlativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedido().setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        
        list_model.vaciar();
        txt_nombre.setText(usuario.getNombre());
        txt_direccion.setText(usuario.getDireccion());
        txt_telefono.setText(usuario.getTelefono() + "");
        txt_nit.setText(usuario.getNit());
        txt_correlativo.setText(ctl_pedido.getLongitud() + "");
        list_articulo.setModel(list_model);
        cmb_model.limpiar();
        for (Articulo objeto : ctl_articulo.getListado()) {
            cmb_model.agregarArticulo(objeto);
        }
        cb_articulo.setModel(cmb_model);
        cb_articulo.setSelectedIndex(-1);
        cb_articulo.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_sesion3;
    private javax.swing.JComboBox<String> cb_articulo;
    private javax.swing.JLabel finalizar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_articulo;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_correlativo;
    private javax.swing.JTextField txt_direccion;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
