/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inventario.vista;

import org.inventario.bean.Entrega;
import org.inventario.bean.EntregaList;
import org.inventario.controlador.ControladorArchivo;
import org.inventario.controlador.ControladorEntrega;

/**
 *
 * @author dafuentes
 */
public class VentanaEstado extends javax.swing.JFrame {

    
    private EntregaList lista_entrega = new EntregaList().getInstance();
    private ControladorArchivo ctl_archivo = new ControladorArchivo().getInstance();
    private ControladorEntrega ctl_entrega = new ControladorEntrega().getInstance();
    /**
     * Creates new form VentanaEstado
     */
    public VentanaEstado() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_regresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_pedido = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_correlativo = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        guardar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresar.png"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setFocusPainted(false);
        btn_regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegresarPressed.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 34, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("Estado Pedido");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, -1, -1));

        list_pedido.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_pedidoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_pedido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 126, 153, 174));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Listado de Pedidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 101, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Correlativo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 173, -1, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette.png"))); // NOI18N
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setFocusPainted(false);
        btn_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette pressed.png"))); // NOI18N
        btn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquette pressed.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 69, -1));

        txt_correlativo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correlativoActionPerformed(evt);
            }
        });
        txt_correlativo.setEditable(false);
        getContentPane().add(txt_correlativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 126, 94, -1));

        cmb_estado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 173, 94, -1));

        guardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardar.setText("Guardar");
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 69, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/White-christmas-light-background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_correlativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correlativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correlativoActionPerformed

    private void list_pedidoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_pedidoValueChanged
        int selection = list_pedido.getSelectedIndex();
        if (selection!=-1) {
            Entrega p = lista_entrega.getEntrega(selection);
            if (p != null) {
                txt_correlativo.setText(p.getId()+ "");
                switch(p.getEstado()) {
                    case "INICIADO":
                        cmb_estado.setSelectedIndex(0);
                        break;
                    case "EN PROCESO":
                        cmb_estado.setSelectedIndex(1);
                        break;
                }
            }
            
            cmb_estado.repaint();
        }
        
    }//GEN-LAST:event_list_pedidoValueChanged

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String estado = cmb_estado.getSelectedItem().toString();
        if (!txt_correlativo.getText().equals("")) {
            ctl_archivo.editarRegistro("Entrega.txt", Integer.parseInt(txt_correlativo.getText()), estado);
            list_pedido.setModel(lista_entrega);
            txt_correlativo.setText("");
            cmb_estado.setSelectedIndex(0);
            cmb_estado.repaint();  
        }
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstado().setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
       
        cmb_estado.addItem("INICIADO");
        cmb_estado.addItem("EN PROCESO");
        cmb_estado.addItem("ENTREGADO");
        list_pedido.setModel(lista_entrega);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_pedido;
    private javax.swing.JTextField txt_correlativo;
    // End of variables declaration//GEN-END:variables
}
